
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Media;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class squiz extends javax.swing.JFrame {

    Clip clipPic;
    Clip buttonClick;
    String category;
    Game newGame;
    int correctAnswer;
    ActionListener timerAction;
   
    
    
    

    /**
     * Creates new form squiz
     */
    public squiz() {

        initComponents();
        URL soundtrack = this.getClass().getClassLoader().getResource("intro.wav");

        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(soundtrack);
            clipPic = AudioSystem.getClip();
            clipPic.open(audio);
            clipPic.loop(5);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(squiz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(squiz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(squiz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        timerAction = new ActionListener()
       {  
        public void actionPerformed(ActionEvent ae)
        {
          changeButtonColor(Color.LIGHT_GRAY );
        }
       };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Categories = new javax.swing.ButtonGroup();
        Squiz = new javax.swing.JTabbedPane();
        options = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        gotButton1 = new javax.swing.JButton();
        intro = new javax.swing.JLabel();
        pregame = new javax.swing.JPanel();
        history = new javax.swing.JRadioButton();
        geography = new javax.swing.JRadioButton();
        science = new javax.swing.JRadioButton();
        health = new javax.swing.JRadioButton();
        technology = new javax.swing.JRadioButton();
        arts = new javax.swing.JRadioButton();
        music = new javax.swing.JRadioButton();
        athletics = new javax.swing.JRadioButton();
        animals = new javax.swing.JRadioButton();
        politics = new javax.swing.JRadioButton();
        playerOne = new javax.swing.JLabel();
        playerTwo = new javax.swing.JLabel();
        userOne = new javax.swing.JTextField();
        userTwo = new javax.swing.JTextField();
        StartButton = new javax.swing.JButton();
        exitiPre = new javax.swing.JButton();
        clear1Button = new javax.swing.JButton();
        clear2Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        back3 = new javax.swing.JLabel();
        rules = new javax.swing.JPanel();
        simpleLabel = new javax.swing.JLabel();
        gotButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        rule1 = new javax.swing.JLabel();
        rule2 = new javax.swing.JLabel();
        rule3 = new javax.swing.JLabel();
        rule4 = new javax.swing.JLabel();
        rule5 = new javax.swing.JLabel();
        rule6 = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        optionsLabel = new javax.swing.JLabel();
        checkBox = new javax.swing.JCheckBox();
        menuButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        information = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        aboutText = new javax.swing.JTextArea();
        back4 = new javax.swing.JLabel();
        ingame = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        secondButton = new javax.swing.JButton();
        thirdButton = new javax.swing.JButton();
        fourthButton = new javax.swing.JButton();
        userTurn = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        catLabel = new javax.swing.JLabel();
        infoCatLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        keepScore = new javax.swing.JLabel();
        runningTime = new javax.swing.JLabel();
        backgroundThree = new javax.swing.JLabel();
        winner = new javax.swing.JPanel();
        playAgain = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        resultBox = new javax.swing.JLabel();
        firstUser = new javax.swing.JLabel();
        firstScore = new javax.swing.JLabel();
        secondUser = new javax.swing.JLabel();
        secondScore = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        test = new javax.swing.JPanel();
        readyButton = new javax.swing.JButton();
        p1Label = new javax.swing.JLabel();
        scoreP1Label = new javax.swing.JLabel();
        readyLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        readyBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQUIZ.IT!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        playButton.setText("Play");
        playButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        playButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        playButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        playButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        options.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 40));

        rulesButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rulesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        rulesButton.setText("Rules");
        rulesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rulesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rulesButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        rulesButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        rulesButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });
        options.add(rulesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 150, 40));

        settingsButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        settingsButton.setText("Settings");
        settingsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        settingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settingsButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        settingsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        settingsButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        options.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 150, 40));

        gotButton1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        gotButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        gotButton1.setText("About");
        gotButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        gotButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gotButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        gotButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        gotButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        gotButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotButton1ActionPerformed(evt);
            }
        });
        options.add(gotButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 150, 40));

        intro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/background.jpg"))); // NOI18N
        intro.setText("jLabel6");
        options.add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, 0, 1440, 620));

        Squiz.addTab("Options", options);

        pregame.setBackground(new java.awt.Color(204, 204, 204));
        pregame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        history.setBackground(new java.awt.Color(255, 204, 51));
        Categories.add(history);
        history.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        history.setText("History");
        history.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/history 3.png"))); // NOI18N
        history.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        history.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        history.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        pregame.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 120, 30));

        geography.setBackground(new java.awt.Color(0, 204, 102));
        Categories.add(geography);
        geography.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        geography.setText("Geography");
        geography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/geography.png"))); // NOI18N
        geography.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        geography.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        geography.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        geography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geographyActionPerformed(evt);
            }
        });
        pregame.add(geography, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 30));

        science.setBackground(new java.awt.Color(0, 204, 204));
        Categories.add(science);
        science.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        science.setText("Science");
        science.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/science.png"))); // NOI18N
        science.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        science.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        science.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceActionPerformed(evt);
            }
        });
        pregame.add(science, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, 30));

        health.setBackground(new java.awt.Color(255, 204, 204));
        Categories.add(health);
        health.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        health.setText("Health & Food");
        health.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/health.png"))); // NOI18N
        health.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        health.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        health.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });
        pregame.add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, 30));

        technology.setBackground(new java.awt.Color(153, 204, 255));
        Categories.add(technology);
        technology.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        technology.setText("Technology");
        technology.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/technology.png"))); // NOI18N
        technology.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        technology.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        technology.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        technology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologyActionPerformed(evt);
            }
        });
        pregame.add(technology, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 120, 30));

        arts.setBackground(new java.awt.Color(251, 133, 189));
        Categories.add(arts);
        arts.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        arts.setText("Arts");
        arts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arts.png"))); // NOI18N
        arts.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        arts.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        arts.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        arts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artsActionPerformed(evt);
            }
        });
        pregame.add(arts, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 30));

        music.setBackground(new java.awt.Color(232, 131, 232));
        Categories.add(music);
        music.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        music.setText("Music & Cinema");
        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/cinema.png"))); // NOI18N
        music.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        music.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        music.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicActionPerformed(evt);
            }
        });
        pregame.add(music, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, 30));

        athletics.setBackground(new java.awt.Color(255, 102, 102));
        Categories.add(athletics);
        athletics.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        athletics.setText("Sports");
        athletics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/sports.png"))); // NOI18N
        athletics.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        athletics.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        athletics.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        athletics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athleticsActionPerformed(evt);
            }
        });
        pregame.add(athletics, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 100, 30));

        animals.setBackground(new java.awt.Color(255, 153, 51));
        Categories.add(animals);
        animals.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        animals.setText("Animals");
        animals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/animals.png"))); // NOI18N
        animals.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        animals.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        animals.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalsActionPerformed(evt);
            }
        });
        pregame.add(animals, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 100, 30));

        politics.setBackground(new java.awt.Color(179, 179, 44));
        Categories.add(politics);
        politics.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        politics.setText("Politics");
        politics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8-elections-30.png"))); // NOI18N
        politics.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/arrow.png"))); // NOI18N
        politics.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        politics.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/check.png"))); // NOI18N
        politics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                politicsActionPerformed(evt);
            }
        });
        pregame.add(politics, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 110, 30));

        playerOne.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        playerOne.setForeground(new java.awt.Color(255, 153, 0));
        playerOne.setText("Player One:");
        pregame.add(playerOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 200, -1));

        playerTwo.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        playerTwo.setForeground(new java.awt.Color(51, 0, 204));
        playerTwo.setText("Player Two:");
        pregame.add(playerTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, -1));
        pregame.add(userOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 166, -1));

        userTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTwoActionPerformed(evt);
            }
        });
        pregame.add(userTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 166, -1));

        StartButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        StartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        StartButton.setText("Start");
        StartButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        StartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StartButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        StartButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        StartButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        pregame.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 130, 40));

        exitiPre.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        exitiPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        exitiPre.setText("Exit");
        exitiPre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        exitiPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitiPre.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        exitiPre.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        exitiPre.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        exitiPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitiPreActionPerformed(evt);
            }
        });
        pregame.add(exitiPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 50, 30));

        clear1Button.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        clear1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        clear1Button.setText("Clear");
        clear1Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        clear1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear1Button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        clear1Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        clear1Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        clear1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ButtonActionPerformed(evt);
            }
        });
        pregame.add(clear1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, 40));

        clear2Button.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        clear2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        clear2Button.setText("Clear");
        clear2Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        clear2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear2Button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        clear2Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        clear2Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        clear2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ButtonActionPerformed(evt);
            }
        });
        pregame.add(clear2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 80, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        pregame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 20, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        pregame.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 189, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("*");
        pregame.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 20, -1));

        warning.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(204, 0, 0));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pregame.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 560, 30));

        back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        pregame.add(back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -100, 1470, 660));

        Squiz.addTab("Pregame", pregame);

        rules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simpleLabel.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        simpleLabel.setForeground(new java.awt.Color(51, 0, 153));
        simpleLabel.setText("Rules:");
        rules.add(simpleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        gotButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        gotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        gotButton.setText("OK");
        gotButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        gotButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gotButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        gotButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        gotButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        gotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotButtonActionPerformed(evt);
            }
        });
        rules.add(gotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 120, 40));

        xButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        xButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        xButton.setText("X");
        xButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        xButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        xButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        xButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });
        rules.add(xButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 40, 30));

        rule1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rule1.setForeground(new java.awt.Color(204, 0, 102));
        rule1.setText("1.You can only select one category per game.");
        rules.add(rule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 550, -1));

        rule2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rule2.setForeground(new java.awt.Color(204, 0, 102));
        rule2.setText("2.The game consists of two rounds with ten questions each.");
        rules.add(rule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 680, 50));

        rule3.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rule3.setForeground(new java.awt.Color(204, 0, 102));
        rule3.setText("3.Each player has 30 seconds to answer.");
        rules.add(rule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 530, 30));

        rule4.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rule4.setForeground(new java.awt.Color(204, 0, 102));
        rule4.setText("4.Each correct answer equals 150 points.");
        rules.add(rule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 570, 40));

        rule5.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        rule5.setForeground(new java.awt.Color(204, 0, 102));
        rule5.setText("5.The player with the highest score is the winner.");
        rules.add(rule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 560, 20));

        rule6.setFont(new java.awt.Font("OCR A Extended", 1, 17)); // NOI18N
        rule6.setForeground(new java.awt.Color(204, 0, 102));
        rule6.setText("6.In case both players have the same score, the winner is both of them. ");
        rules.add(rule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 720, 60));

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        rules.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -70, 1460, 610));

        Squiz.addTab("Rules", rules);

        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        optionsLabel.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        optionsLabel.setForeground(new java.awt.Color(102, 0, 255));
        optionsLabel.setText("Options Sound:");
        settings.add(optionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 340, 140));

        checkBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/sound (2).png"))); // NOI18N
        checkBox.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/mute.png"))); // NOI18N
        checkBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/sound (2).png"))); // NOI18N
        checkBox.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/mute.png"))); // NOI18N
        checkBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/mute.png"))); // NOI18N
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });
        settings.add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 110, 80));

        menuButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        menuButton.setText("Menu");
        menuButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        menuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        menuButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        menuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        settings.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 120, 30));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        settings.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -90, 1440, 630));

        Squiz.addTab("Settings", settings);

        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        information.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        information.setForeground(new java.awt.Color(153, 0, 153));
        information.setText("ABOUT:");
        about.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 230, 90));

        backButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        backButton.setText("<<Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        backButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        backButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        about.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 120, 40));

        aboutText.setColumns(20);
        aboutText.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        aboutText.setRows(5);
        aboutText.setText("This is a simple application that was developed for the subject of \nInteraction of Humans - Computers.\n\nThis is only for the presentation procedure.\nDeveloped by: Chrisanthi Sidiropolou & John Stefanidis\n ");
        aboutText.setEnabled(false);
        about.add(aboutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 660, 250));

        back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        about.add(back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -70, 1470, 620));

        Squiz.addTab("About", about);

        ingame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstButton.setForeground(new java.awt.Color(51, 51, 0));
        firstButton.setText("A");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        ingame.add(firstButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 200, 70));

        secondButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        secondButton.setForeground(new java.awt.Color(51, 51, 0));
        secondButton.setText("B");
        secondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButtonActionPerformed(evt);
            }
        });
        ingame.add(secondButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 210, 70));

        thirdButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        thirdButton.setForeground(new java.awt.Color(51, 51, 0));
        thirdButton.setText("C");
        thirdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdButtonActionPerformed(evt);
            }
        });
        ingame.add(thirdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 200, 70));

        fourthButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fourthButton.setForeground(new java.awt.Color(51, 51, 0));
        fourthButton.setText("D");
        fourthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthButtonActionPerformed(evt);
            }
        });
        ingame.add(fourthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 210, 70));

        userTurn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userTurn.setForeground(new java.awt.Color(255, 204, 51));
        userTurn.setText("Player number one is playing.");
        ingame.add(userTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 114, 250, 30));

        questionLabel.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(153, 0, 153));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("The questions of each category will appear here:");
        questionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingame.add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 640, 70));

        catLabel.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        catLabel.setForeground(new java.awt.Color(189, 96, 191));
        catLabel.setText("Category ");
        ingame.add(catLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 230, 50));

        infoCatLabel.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        infoCatLabel.setText("Selected Category:");
        ingame.add(infoCatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, 50));

        scoreLabel.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 0, 153));
        scoreLabel.setText("Score:");
        ingame.add(scoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 30));

        keepScore.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        keepScore.setForeground(new java.awt.Color(51, 0, 204));
        keepScore.setText("Test");
        ingame.add(keepScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 100, 50));

        runningTime.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        runningTime.setText("     ");
        ingame.add(runningTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 60, 30));

        backgroundThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        ingame.add(backgroundThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -70, 1450, 620));

        Squiz.addTab("InGame", ingame);

        winner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playAgain.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        playAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        playAgain.setText("Play Again");
        playAgain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        playAgain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playAgain.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        playAgain.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        playAgain.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainActionPerformed(evt);
            }
        });
        winner.add(playAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 120, 30));

        exitButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        exitButton.setText("X");
        exitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        exitButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        exitButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        winner.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 40, 30));

        resultBox.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        resultBox.setForeground(new java.awt.Color(255, 255, 255));
        resultBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultBox.setText("DEPENDS ON RESULT");
        resultBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        winner.add(resultBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 210, 50));

        firstUser.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        firstUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstUser.setText("userWinner");
        winner.add(firstUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 180, -1));

        firstScore.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        firstScore.setForeground(new java.awt.Color(255, 51, 51));
        firstScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstScore.setText("SCORE");
        winner.add(firstScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 80, -1));

        secondUser.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        secondUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondUser.setText("userTwo");
        winner.add(secondUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        secondScore.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        secondScore.setForeground(new java.awt.Color(255, 0, 51));
        secondScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondScore.setText("SCORE");
        winner.add(secondScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 80, 20));

        winnerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/winner.jpg"))); // NOI18N
        winner.add(winnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-530, -30, 1460, 620));

        Squiz.addTab("Winner", winner);

        test.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        readyButton.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        readyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yellow.jpg"))); // NOI18N
        readyButton.setText("Ready");
        readyButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        readyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        readyButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        readyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey.jpeg"))); // NOI18N
        readyButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/grey2.jpg"))); // NOI18N
        readyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButtonActionPerformed(evt);
            }
        });
        test.add(readyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 120, 40));

        p1Label.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        p1Label.setForeground(new java.awt.Color(255, 153, 0));
        p1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Label.setText("PlayerOne");
        test.add(p1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 240, 30));

        scoreP1Label.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        scoreP1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP1Label.setText("Score");
        test.add(scoreP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 180, 40));

        readyLabel.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        readyLabel.setForeground(new java.awt.Color(51, 0, 204));
        readyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        readyLabel.setText("Its players two turn. ");
        readyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        test.add(readyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 380, 100));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Press ready to proceed to second round.");
        test.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 440, 20));

        readyBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/b2.jpg"))); // NOI18N
        test.add(readyBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -60, 1440, 600));

        Squiz.addTab("Test", test);

        getContentPane().add(Squiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -29, 890, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicActionPerformed
        this.category = music.getText();
    }//GEN-LAST:event_musicActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        this.category = history.getText();
    }//GEN-LAST:event_historyActionPerformed

    private void gotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotButtonActionPerformed
        Squiz.setSelectedIndex(1);
    }//GEN-LAST:event_gotButtonActionPerformed

    private void userTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTwoActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed

        Squiz.setSelectedIndex(1);

    }//GEN-LAST:event_playButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        Squiz.setSelectedIndex(3);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void gotButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotButton1ActionPerformed
        Squiz.setSelectedIndex(4);
    }//GEN-LAST:event_gotButton1ActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        Squiz.setSelectedIndex(2);
    }//GEN-LAST:event_rulesButtonActionPerformed

    private void scienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceActionPerformed
        this.category = science.getText();
    }//GEN-LAST:event_scienceActionPerformed

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        this.category = health.getText();
    }//GEN-LAST:event_healthActionPerformed

    private void technologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologyActionPerformed
        this.category = technology.getText();
    }//GEN-LAST:event_technologyActionPerformed

    private void geographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geographyActionPerformed
        this.category = geography.getText();
    }//GEN-LAST:event_geographyActionPerformed

    private void athleticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_athleticsActionPerformed
        this.category = athletics.getText();
    }//GEN-LAST:event_athleticsActionPerformed

    private void animalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalsActionPerformed
        this.category = animals.getText();
    }//GEN-LAST:event_animalsActionPerformed

    private void politicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_politicsActionPerformed
        this.category = politics.getText();
    }//GEN-LAST:event_politicsActionPerformed

    private void artsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artsActionPerformed
        this.category = arts.getText();
    }//GEN-LAST:event_artsActionPerformed

    private void clear1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ButtonActionPerformed
        userOne.setText("");
    }//GEN-LAST:event_clear1ButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        changeButtonColor(Color.LIGHT_GRAY);
        Player playerOne = new Player(userOne.getText());
        Player playerTwo = new Player(userTwo.getText());
        newGame = new Game(playerOne, playerTwo, category);
        if(checkPregameFields()){
            warning.setText("Username not assigned or catgory not selected.");
        }
        else{
        Squiz.setSelectedIndex(5);
        catLabel.setText(newGame.getSelectedCategory());
        userTurn.setText(newGame.getPlayingPlayer().getName() + " is playing:");
        setQuestionAndCandidateAnswers();
        keepScore.setText(String.valueOf(newGame.getPlayingPlayer().getScore()));
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void clear2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ButtonActionPerformed
        userTwo.setText("");
    }//GEN-LAST:event_clear2ButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        Squiz.setSelectedIndex(0);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Squiz.setSelectedIndex(0);
    }//GEN-LAST:event_backButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        checkAnswer(firstButton);


    }//GEN-LAST:event_firstButtonActionPerformed

    private void secondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondButtonActionPerformed

        checkAnswer(secondButton);
    }//GEN-LAST:event_secondButtonActionPerformed

    private void thirdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdButtonActionPerformed

        checkAnswer(thirdButton);
    }//GEN-LAST:event_thirdButtonActionPerformed

    private void fourthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthButtonActionPerformed

        checkAnswer(fourthButton);
    }//GEN-LAST:event_fourthButtonActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainActionPerformed
        Squiz.setSelectedIndex(1);
    }//GEN-LAST:event_playAgainActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Squiz.setSelectedIndex(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        if (checkBox.isSelected()) {
            clipPic.stop();
        } else if (!checkBox.isSelected()) {
            clipPic.start();
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    private void exitiPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitiPreActionPerformed
        Squiz.setSelectedIndex(0);
    }//GEN-LAST:event_exitiPreActionPerformed

    private void readyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButtonActionPerformed

        Squiz.setSelectedIndex(5);
    }//GEN-LAST:event_readyButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        Squiz.setSelectedIndex(0);
    }//GEN-LAST:event_xButtonActionPerformed

    private void checkAnswer(JButton button) {

        if (button.getText().equals(newGame.getCorrectAnswer())) {
            button.setBackground(Color.GREEN);
            newGame.getPlayingPlayer().increaseAndGetScore();
            keepScore.setText(String.valueOf(newGame.getPlayingPlayer().getScore()));
            refreshPlayer();
        } else {
            button.setBackground(Color.RED);
             refreshPlayer();
        }
        userTurn.setText(newGame.getPlayingPlayer().getName() + " is playing:");
        keepScore.setText(String.valueOf(newGame.getPlayingPlayer().getScore()));
   
        Timer timer = new Timer(800, timerAction);
        timer.start();
        newGame.setIndexOfQuestionInPlay();
        setQuestionAndCandidateAnswers();
        if (newGame.endOfGame()) {
            Squiz.setSelectedIndex(6);
            getTheWinner();
        }
    }

    private void changeButtonColor(Color color) {
        firstButton.setBackground(color);
        secondButton.setBackground(color);
        thirdButton.setBackground(color);
        fourthButton.setBackground(color);
    }
    
    private void refreshPlayer() {
        if (newGame.getQuestionsCounter() == (newGame.getMaxQuestionsPerRound()-1)) {
            Squiz.setSelectedIndex(7);
            p1Label.setText(newGame.getPlayerOne().getName());
            scoreP1Label.setText(String.valueOf(newGame.getPlayerOne().getScore()));
            readyLabel.setText(newGame.getPlayerTwo().getName() + "'s turn!");
            newGame.setPlayingPlayer(newGame.getPlayerTwo());
        }
    }
    
    private void setQuestionAndCandidateAnswers(){
        questionLabel.setText(newGame.getQuestionInPlay().getQuestion());
        firstButton.setText(newGame.getQuestionInPlay().getAnswers()[0]);
        secondButton.setText(newGame.getQuestionInPlay().getAnswers()[1]);
        thirdButton.setText(newGame.getQuestionInPlay().getAnswers()[2]);
        fourthButton.setText(newGame.getQuestionInPlay().getAnswers()[3]);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(squiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(squiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(squiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(squiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new squiz().setVisible(true);
            }
        });
    }
     
 
    
    
    private void getTheWinner(){
        if (newGame.getPlayerOne().getScore() > newGame.getPlayerTwo().getScore()) {
                resultBox.setText("WE HAVE WINNER!");
                firstUser.setText(String.valueOf(newGame.getPlayerOne().getName()));
                firstScore.setText(String.valueOf(newGame.getPlayerOne().getScore()));
                secondUser.setText(String.valueOf(newGame.getPlayerTwo().getName()));
                secondScore.setText(String.valueOf(newGame.getPlayerTwo().getScore()));
            } else if (newGame.getPlayerOne().getScore() < newGame.getPlayerTwo().getScore()) {
                resultBox.setText("WE HAVE WINNER!");
                firstUser.setText(String.valueOf(newGame.getPlayerTwo().getName()));
                firstScore.setText(String.valueOf(newGame.getPlayerTwo().getScore()));
                secondUser.setText(String.valueOf(newGame.getPlayerOne().getName()));
                secondScore.setText(String.valueOf(newGame.getPlayerOne().getScore()));
            } else {
                resultBox.setText("IT'S A DRAW");
                firstUser.setText(String.valueOf(newGame.getPlayerOne().getName()));
                firstScore.setText(String.valueOf(newGame.getPlayerOne().getScore()));
                secondUser.setText(String.valueOf(newGame.getPlayerTwo().getName()));
                secondScore.setText(String.valueOf(newGame.getPlayerTwo().getScore()));
            }
    }
    private void setColorInButton(JButton button) {

        button.setBackground(Color.LIGHT_GRAY);
    }
    
    private boolean checkPregameFields(){
        return newGame.getPlayerOne().getName()==null || newGame.getPlayerTwo().getName()==null || newGame.getPlayerOne().getName().isBlank() || newGame.getPlayerTwo().getName().isBlank() || newGame.getSelectedCategory() == null ||newGame.getSelectedCategory().isBlank();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Categories;
    private javax.swing.JTabbedPane Squiz;
    private javax.swing.JButton StartButton;
    private javax.swing.JPanel about;
    private javax.swing.JTextArea aboutText;
    private javax.swing.JRadioButton animals;
    private javax.swing.JRadioButton arts;
    private javax.swing.JRadioButton athletics;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel back3;
    private javax.swing.JLabel back4;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel backgroundThree;
    private javax.swing.JLabel catLabel;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton clear1Button;
    private javax.swing.JButton clear2Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitiPre;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel firstScore;
    private javax.swing.JLabel firstUser;
    private javax.swing.JButton fourthButton;
    private javax.swing.JRadioButton geography;
    private javax.swing.JButton gotButton;
    private javax.swing.JButton gotButton1;
    private javax.swing.JRadioButton health;
    private javax.swing.JRadioButton history;
    private javax.swing.JLabel infoCatLabel;
    private javax.swing.JLabel information;
    private javax.swing.JPanel ingame;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel keepScore;
    private javax.swing.JButton menuButton;
    private javax.swing.JRadioButton music;
    private javax.swing.JPanel options;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JLabel p1Label;
    private javax.swing.JButton playAgain;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel playerOne;
    private javax.swing.JLabel playerTwo;
    private javax.swing.JRadioButton politics;
    private javax.swing.JPanel pregame;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel readyBackground;
    private javax.swing.JButton readyButton;
    private javax.swing.JLabel readyLabel;
    private javax.swing.JLabel resultBox;
    private javax.swing.JLabel rule1;
    private javax.swing.JLabel rule2;
    private javax.swing.JLabel rule3;
    private javax.swing.JLabel rule4;
    private javax.swing.JLabel rule5;
    private javax.swing.JLabel rule6;
    private javax.swing.JPanel rules;
    private javax.swing.JButton rulesButton;
    private javax.swing.JLabel runningTime;
    private javax.swing.JRadioButton science;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreP1Label;
    private javax.swing.JButton secondButton;
    private javax.swing.JLabel secondScore;
    private javax.swing.JLabel secondUser;
    private javax.swing.JPanel settings;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel simpleLabel;
    private javax.swing.JRadioButton technology;
    private javax.swing.JPanel test;
    private javax.swing.JButton thirdButton;
    private javax.swing.JTextField userOne;
    private javax.swing.JLabel userTurn;
    private javax.swing.JTextField userTwo;
    private javax.swing.JLabel warning;
    private javax.swing.JPanel winner;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JButton xButton;
    // End of variables declaration//GEN-END:variables
}
